name: Build iOS App for Sideloading

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
        npx expo install --fix
        
    - name: Setup EAS CLI
      run: npm install -g @expo/eas-cli@latest
      
    - name: Login to Expo
      run: eas login --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
    - name: Build iOS App
      run: eas build --platform ios --profile standalone --non-interactive --wait
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
    - name: Download build artifacts
      run: |
        mkdir -p artifacts
        eas build:list --platform ios --limit 1 --json > build-info.json
        BUILD_URL=$(cat build-info.json | jq -r '.[0].artifacts.buildUrl')
        curl -L -o artifacts/momentum.ipa "$BUILD_URL"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: artifacts/*.ipa
        retention-days: 30
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ios-build-${{ github.run_number }}
        name: iOS App Build ${{ github.run_number }}
        body: |
          🍎 **iOS App Build Ready for Sideloading**
          
          This build contains a standalone iOS app that can be installed directly on your iPhone without an Apple Developer account.
          
          **Installation Instructions:**
          1. Download the `.ipa` file below
          2. Use AltStore, Sideloadly, or similar tool to install
          3. Or install directly via Safari on iOS 17+ (EU only)
          
          **Requirements:**
          - iOS 13.0 or later
          - iPhone/iPad
          
          Built on: ${{ github.event.head_commit.timestamp }}
        files: artifacts/*.ipa
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
