name: Build iOS App - Pure Web Approach

on:
  workflow_dispatch:

jobs:
  build-ios-web:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps --force
        
    - name: Build web app
      run: npm run build
        
    - name: Create iOS app structure
      run: |
        mkdir -p ios-app/Payload
        cp -r dist/* ios-app/Payload/
        
    - name: Create Info.plist
      run: |
        cat > ios-app/Payload/Info.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleDisplayName</key>
            <string>Momentum</string>
            <key>CFBundleExecutable</key>
            <string>Momentum</string>
            <key>CFBundleIdentifier</key>
            <string>com.momentum.productivityapp</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>Momentum</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0.0</string>
            <key>CFBundleVersion</key>
            <string>1</string>
            <key>LSRequiresIPhoneOS</key>
            <true/>
            <key>UILaunchStoryboardName</key>
            <string>LaunchScreen</string>
            <key>UIRequiredDeviceCapabilities</key>
            <array>
                <string>armv7</string>
            </array>
            <key>UISupportedInterfaceOrientations</key>
            <array>
                <string>UIInterfaceOrientationPortrait</string>
                <string>UIInterfaceOrientationLandscapeLeft</string>
                <string>UIInterfaceOrientationLandscapeRight</string>
            </array>
            <key>UISupportedInterfaceOrientations~ipad</key>
            <array>
                <string>UIInterfaceOrientationPortrait</string>
                <string>UIInterfaceOrientationPortraitUpsideDown</string>
                <string>UIInterfaceOrientationLandscapeLeft</string>
                <string>UIInterfaceOrientationLandscapeRight</string>
            </array>
        </dict>
        </plist>
        EOF
        
    - name: Create IPA package
      run: |
        cd ios-app
        zip -r ../momentum.ipa Payload/
        cd ..
        ls -la *.ipa
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-web-build
        path: *.ipa
        retention-days: 30
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ios-web-build-${{ github.run_number }}
        name: iOS Web App Build ${{ github.run_number }}
        body: |
          🌐 **iOS Web App Build Ready for Sideloading**
          
          This is a web-based iOS app that can be installed directly on your iPhone.
          
          **Installation Instructions:**
          1. Download the `.ipa` file below
          2. Use AltStore, Sideloadly, or similar tool to install
          3. Or install directly via Safari on iOS 17+ (EU only)
          
          **Note:** This is a web app packaged as iOS app - it will work offline after installation.
          
          Built on: ${{ github.event.head_commit.timestamp }}
        files: *.ipa
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
